### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by Wizzard033**

### CODE REVIEW

**Comment by neomantra** [comment]
@Wizzard033 Thanks for sending this over!

I hadn't looked at this for quite a while.   In reviewing the whole file with fresh eyes, I think that returning `nil` when there is no object is a better API.  It is much more The Lua Way.

Do you want to make that change?  Otherwise I can do it quick....

I would update `Array:get`, `Array:get_e` (docs only), `Array:front`, `Array:back` (docs).
`Array:set` is fine as is because it's returning an error, not an object.

Also, `Vector:get`, `Vector:front`, `Vector:back`, `Vector:pop_back`

Thoughts?

**Comment by Wizzard033** [comment]
I agree with and already made that change locally 👍

**Comment by neomantra** [comment]
Sweet, please do that to `Vector.lua` and i'll merge.  Many thanks!

**Comment by neomantra** [comment]
Merged, thanks again!

**Pull request merged**
